apiVersion: v1
kind: ConfigMap
metadata:
  name: forest-fire-backend-config
  namespace: forest-fire
  labels:
    app: forest-fire-backend
data:
  PORT: "8000"
  STORAGE_PROVIDER: "local"
  STORAGE_BASE_DIR: "/app/storage"
  LOG_LEVEL: "info"
