apiVersion: v1
kind: Service
metadata:
  name: ignisai-backend-service
  namespace: ignisai-production
spec:
  type: ClusterIP
  selector:
    app: ignisai-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
